# Exception Handling

Any try/catch/finally blocks in effect when a thread is created are of no relevance to the thread when it starts executing. Consider the following program:

```c#
try {
  new Thread (Go).Start();
}
catch (Exception ex) {
  // We'll never get here!
  Console.WriteLine ("Exception!");
 }
void Go() { throw null; }   // Throws a NullReferenceException

```

The try/catch statement in this example is ineffective, and the newly created thread will be encumbered with an unhandled NullReferenceException. This behavior makes sense when you consider that each thread has an independent execution path.
The remedy is to move the exception handler into the Go method:

```c#
new Thread (Go).Start();
void Go() {
try {
    ...
    throw null;
    ...
    // The NullReferenceException will get caught below
      }
      catch (Exception ex)
      {
        // Typically log the exception and/or signal another thread
        // that we've come unstuck
        ...
} }
```

# Centralized exception handling

In WPF, UWP, and Windows Forms applications, you can subscribe to “global” exception handling events, Application.DispatcherUnhandledException and Application.ThreadException, respectively. These fire after an unhandled excep‐ tion in any part of your program that’s called via the message loop (this amounts to all code that runs on the main thread while the Application is active). This is useful as a backstop for logging and reporting bugs (although it won’t fire for unhandled exceptions on worker threads that you create). Handling these events prevents the program from shutting down, although you may choose to restart the application to avoid the potential corruption of state that can follow from (or that led to) the unhandled exception.

```c#
using System;
using System.Windows.Forms;

namespace ExceptionHandlingExample
{
    static class Program
    {
        [STAThread]
        static void Main()
        {
            Application.EnableVisualStyles();
            Application.SetCompatibleTextRenderingDefault(false);

            // Subscribe to the Application.ThreadException event
            Application.ThreadException += new System.Threading.ThreadExceptionEventHandler(Application_ThreadException);

            // Run the main form
            Application.Run(new MainForm());
        }

        static void Application_ThreadException(object sender, System.Threading.ThreadExceptionEventArgs e)
        {
            // Handle the exception here
            MessageBox.Show($"An error has occurred: {e.Exception.Message}");
        }
    }

    public partial class MainForm : Form
    {
        public MainForm()
        {
            InitializeComponent();
        }

        private void btnThrowException_Click(object sender, EventArgs e)
        {
            // This will throw an exception
            throw new Exception("An error has occurred.");
        }
    }
}

```
